name: icalendar
version: 0.1.0
description: >-
  Dart package to serialize/deserialize iCalendar text.
homepage: https://gitlab.com/powerbuilding/mobile/support-libraries/ical
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  email_validator: ^2.1.17
  equatable: ^2.0.5
  intl: ^0.18.0
  nanoid: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.19.3
