name: ical
version: 0.2.2
description: >-
  A library to generate/serialize iCalendar files
homepage: https://gitlab.com/powerbuilding/mobile/support-libraries/ical
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  nanoid: ^1.0.0

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.19.3
